### ISSUE TITLE
make completion aware of "with" scopes

### ISSUE THREAD

**Issue by Prince781** [Prince781/vala-language-server#122]
Vala 0.50 adds the `with` keyword, which allows you to implicitly access a member of an expression. See [this commit](https://gitlab.gnome.org/GNOME/vala/-/commit/35f72f3ecdf0d61d0e67cd4f72c29fee2c3c9a55).

**Comment by gavr123456789** [comment]
Example
```vala
string s = "s";
with (s) {
	has_prefix("a");
	//autocomplete here shows only string.* related methods
}

**Comment by gavr123456789** [comment]
not only completeeon, but also usual auto complition  
![image](https://user-images.githubusercontent.com/30507409/103350887-7efbd700-4ab2-11eb-98b4-6ffbe7a4899f.png)

**Comment by Prince781** [comment]
@gavr123456789 that's not a problem with usual auto completion, because the `label` symbol is for some reason undefined
