### ISSUE TITLE
VLS suggest "throw" instead of "throws" in function signatures

### ISSUE THREAD

**Issue by Cogitri** [Prince781/vala-language-server#133]
**Describe the bug**
When editing the function signature to add a new error that can be thrown VLS suggests `throw` instead of `throws`:

![Screenshot from 2020-07-02 09-33-03](https://user-images.githubusercontent.com/8766773/86330015-53a14800-bc47-11ea-9673-6368f8fd183c.png)

This is something rather minor, but I tend to fall for it every time, so I figured it'd be best to report it :)

**Software**
OS and version (e.g. Ubuntu 20.04): Alpine Linux Edge
Code editor (e.g. VSCode): VSCode
Vala Language Server (e.g. git commit, or PPA/AUR version): Tested with 0.48.0 and latest git (1307a92f762c381d8a7b0183f084bb77cf726fa0)
Vala version (`valac --version`): Vala 0.48.7

**To Reproduce**
1. Write function declaration
2. Try to add `throws` statement, VLS will only suggest `throw`

**Comment by Prince781** [comment]
This is basically an issue with context-sensitive completion, which is an area that VLS is in its infancy in.
