### ISSUE TITLE
Upstream the GNOME Builder plugin

### ISSUE THREAD

**Issue by abderrahim** [Prince781/vala-language-server#156]
**Describe the bug**

It would be nice to have the gnome-builder plugin as part of upstream (which is also upstream's policy regarding plugins). The plugin hasn't seen any real change (except compatibility fixes) since https://github.com/benwaffle/vala-language-server/commit/26cce4359991840bd87c0e959f8e3537a4e8a4d5, so it's not like upstreaming it will make development harder.

It will also help with https://github.com/benwaffle/vala-language-server/issues/103

**Comment by overlisted** [comment]
Please do it! I really don't like constantly copying compiled `vala_langserv.*` to `~/.local/share/flatpak/app/org.gnome.Builder/x86_64/master/{revision}/files/lib/gnome-builder/plugins`

**Comment by Prince781** [comment]
See https://gitlab.gnome.org/GNOME/gnome-builder/-/merge_requests/391
