### ISSUE TITLE
Display stdout of failed meson run in output console

### ISSUE THREAD

**Issue by Cogitri** [Prince781/vala-language-server#158]
**Describe the bug**
It'd be helpful if VLS opened a terminal in VSCode when configuring with meson failed and it displayed meson's output

**Comment by Prince781** [comment]
Or perhaps I'm misunderstanding your issue.

**Comment by Cogitri** [comment]
Ah yes, seems like VLS does write this to its `Output` tab (even without debug mode), but I doubt users will look there for the logs. I think it'd be useful if the output tab were opened like it is when VLS crashes so users immediately see what exactly went wrong. On the other hand, maybe it's OK assuming that if the user sees the error message from VLS that configuration went wrong they'll open a terminal and run meson themselves to check what is wrong

**Comment by Prince781** [comment]
If VLS crashes then (at least in Visual Studio Code) the output tab's information should persist. There may be something in settings that affects this behavior, though.

**Comment by Prince781** [comment]
So is this really an issue, then? Can I close it? It doesn't seem to be behavior controlled by the language server.

**Comment by Cogitri** [comment]
Hmm, well, IMHO it'd still be nice if the VSCode Extension would throw a separate error "Meson configure failed..." and showed that to the user

**Comment by Prince781** [comment]
Seeing as this is the present behavior of VLS, I'm closing this. If you think of something else, or if I misunderstood this issue, feel free to reopen.
