### ISSUE TITLE
support Meson subprojects

### ISSUE THREAD

**Issue by nahuelwexd** [Prince781/vala-language-server#162]
**Describe the bug**
VLS stops working when I add libhandy in gtk4 branch as subproject. It accuses that it cannot find the GIR file, but as I could see it is never generated when it compiles the library. Maybe it's compiling it wrong?

**Software**
OS and version (e.g. Ubuntu 20.04): Fedora 33 (Silverblue). Running VLS from Toolbox
Code editor (e.g. VSCode): VS Code. Running it from Toolbox
Vala Language Server (e.g. git commit, or PPA/AUR version): Latest from master (61ae142bd2c279b2ff4881bfd9010ccd22a7b215)
Vala version (`valac --version`): 0.48.11

**To Reproduce**
Source code repo: https://github.com/nahuelwexd/Replay

1. Open the repo
2. Open any Vala file
3. Wait until the Output panel is opened with the error printed

**Comment by Prince781** [comment]
Meson subprojects aren't supported yet.

**Comment by nahuelwexd** [comment]
I thought they were because they had started working quite well with the latest versions 🤔

**Comment by Prince781** [comment]
I haven't done any testing with them, nor made any specific effort to support them, so if they work that's just a coincidence.

**Comment by Cogitri** [comment]
Seems like they work for my vala-unit subproject too :thinking:

**Comment by Cogitri** [comment]
Maybe VLS could support passing on `PKG_CONFIG_PATH` to meson as a workaround for this, then it'd be possible to install subprojects to some folder

**Comment by Prince781** [comment]
It turns out that this and #168 are both caused by issues with command substitution and dependency resolution in Meson projects.
