### ISSUE TITLE
document how VLS gets compiler flags

### ISSUE THREAD

**Issue by zocker-160** [Prince781/vala-language-server#167]
EDIT: this is not a bug, but a lack of documentation, since beginners like me don't know the dependency on additional files needed in order to make it work properly.

old bug report:
--------------
**Describe the bug**
I am trying to learn Vala by using some of the official Vala GTK+ examples, but sadly I don't get any suggestions for the Gtk module. It complains about not finding it, while I am able to compile the code with `valac --pkg gtk+-3.0 tmp.vala` no problem.

![Screenshot_20201105_014628](https://user-images.githubusercontent.com/36563538/98183575-bada4c00-1f08-11eb-88a4-d14a8da516c1.png)

Also I don't have that vala-language-server tab on the left side, like in [this screenshot](https://raw.githubusercontent.com/benwaffle/vala-language-server/master/images/vls-vscode.png).

**Software**
OS and version (e.g. Ubuntu 20.04): Ubuntu 20.04 LTS
Code editor (e.g. VSCode): VSCode 1.50.1
Vala Language Server (e.g. git commit, or PPA/AUR version): from OBS repo
Vala version (`valac --version`): 0.48.6

**To Reproduce**
Source code repo: https://wiki.gnome.org/Projects/Vala/GTKSample

1. install VSCode
2. install VSCode vala plugin (prince781.vala)
3. install VLS from OBS repo
4. create new `tmp.vala` file and copy sample code into it
5. open`tmp.vala` with VSCode editor

**Comment by Prince781** [comment]
This is not an issue (see https://github.com/benwaffle/vala-language-server/issues/161). VLS doesn't have the compiler arguments because it needs to get them either from `compile_commands.json` or a `meson.build` file in the project structure. In fact, there's actually no good way to know what package you want when you write `using Gtk;`, since that namespace belongs to several packages (GTK2, GTK3, and GTK4).

**Comment by zocker-160** [comment]
@Prince781 ok thanks understood, but I would suggest adding that info to the readme or at least add a reference to https://github.com/benwaffle/vala-starter, because I think many other beginners will also bump into this issue.

**Comment by Prince781** [comment]
@zocker-160 good point. I'll transform this ticket into _that_ issue then.

**Comment by zocker-160** [comment]
thank you, I updated the description of the issue and using the `vala-starter` repo as template, I got it working now
I apologize for the false report.
