### ISSUE TITLE
failing with simple project

### ISSUE THREAD

**Issue by knuxbbs** [Prince781/vala-language-server#184]
**Describe the bug**
Vala types like `int` and `string` are not recognized by the language server.

**Software**
OS and version (e.g. Ubuntu 20.04): Ubuntu 20.04
Code editor (e.g. VSCode): VSCode
Vala Language Server (e.g. git commit, or PPA/AUR version): 0.48.0
Vala version (`valac --version`): 0.52.2

**To Reproduce**
In Gnome Builder, I've created a sample Gnome application with Vala. When I try to open it with Visual Studio Code, auto-complete doesn't work, and I get the following issues with built-in types.

![Captura de tela de 2021-05-05 13-24-04](https://user-images.githubusercontent.com/2906620/117189103-2f0c8400-adb4-11eb-91db-ef0806d38b7c.png)

I've created a repo with the source code of the project: https://github.com/knuxbbs/vala-sample. And this is the Vala Language Server log on the VSCode output tab: [vls.log](https://github.com/Prince781/vala-language-server/files/6429389/vls.log). I suspect that the error is related with these lines:

> Error: Package `gobject-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
> Error: Package `gtk+-3.0' not found in specified Vala API directories or GObject-Introspection GIR directories
> Error: Package `glib-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
> Error: Package `gio-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
> Error: Package `gobject-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
> Error: Package `gtk+-3.0' not found in specified Vala API directories or GObject-Introspection GIR directories
> Error: Package `glib-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
> Error: Package `gio-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
> Error: The namespace name `GLib' could not be found
> Error: The namespace name `GLib' could not be found

Any clues of how can I solve this problem? I really interested in learning Vala, but without a good developer experience, this can be hard.

**Comment by Prince781** [comment]
You need to include `build-aux/meson/postinstall.py`

```
The Meson build system
Version: 0.58.0
Source dir: /home/pferro/Projects/vala-sample
Build dir: /home/pferro/Projects/vala-sample/build
Build type: native build
Project name: valasample
Project version: 0.1.0
C compiler for the host machine: ccache cc (gcc 10.2.0 "cc (GCC) 10.2.0")
C linker for the host machine: cc ld.bfd 2.36.1
Vala compiler for the host machine: valac (valac 0.52.3)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program desktop-file-validate found: YES (/usr/bin/desktop-file-validate)
Program appstream-util found: YES (/usr/bin/appstream-util)
Program glib-compile-schemas found: YES (/usr/bin/glib-compile-schemas)
Found pkg-config: /usr/bin/pkg-config (1.7.3)
Run-time dependency gio-2.0 found: YES 2.68.1
Run-time dependency gtk+-3.0 found: YES 3.24.29
Found pkg-config: /usr/bin/pkg-config (1.7.3)
Program glib-compile-resources found: YES (/usr/bin/glib-compile-resources)
Program build-aux/meson/postinstall.py found: NO

meson.build:15:6: ERROR: Program 'build-aux/meson/postinstall.py' not found
```

**Comment by Prince781** [comment]
Another thing, you need to enable debug mode for the Vala plugin in VS Code. That way the log you generate will include a lot more useful information. However, I will still have something to work with here.
![Screenshot from 2021-05-05 15-39-30](https://user-images.githubusercontent.com/1341033/117199500-451c4380-adb8-11eb-9cbe-68439c1d8047.png)

**Comment by knuxbbs** [comment]
I added the missing file: https://github.com/knuxbbs/vala-sample/commit/91e0a161f00a993f052b2d3d178db009280e494e.

And here is the log with debug enabled: [vls.log](https://github.com/Prince781/vala-language-server/files/6430285/vls.log)

**Comment by Prince781** [comment]
Okay, I see the issue now. You're using an old version of VLS (0.48.0). You need the latest version. Unfortunately you need to compile and install VLS like `meson -Dprefix=/usr build` (the prefix is important) because the Ubuntu 20.04 package does not build.

**Comment by Prince781** [comment]
So I'm closing this as I assume this issue is resolved in the latest version of VLS.
