### ISSUE TITLE
E: Failed to fetch http://ppa.launchpad.net/prince781/vala-language-server/ubuntu/dists/bionic/InRelease  403  Forbidden [IP: 2001:67c:1560:8008::19 80]

### ISSUE THREAD

**Issue by klascano** [Prince781/vala-language-server#211]
**Describe the bug**
can fetch ppa

**Software**
LSB Version:	core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	elementary
Description:	elementary OS 5.1.7 Hera
Release:	5.1.7
Codename:	hera

**To Reproduce**
sudo apt update && sudo apt upgrade

Err:29 http://ppa.launchpad.net/prince781/vala-language-server/ubuntu bionic InRelease                                                                                                                
  403  Forbidden [IP: 2001:67c:1560:8008::19 80]
Hit:30 http://ppa.launchpad.net/ricotz/docky/ubuntu bionic InRelease                                                                                                                                  
Hit:31 http://ppa.launchpad.net/vala-team/next/ubuntu bionic InRelease                                                                                                                                
Reading package lists... Done                                                                                                                                                                         
E: Failed to fetch http://ppa.launchpad.net/prince781/vala-language-server/ubuntu/dists/bionic/InRelease  403  Forbidden [IP: 2001:67c:1560:8008::19 80]
E: The repository 'http://ppa.launchpad.net/prince781/vala-language-server/ubuntu bionic InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by Prince781** [comment]
The PPA has been deprecated since earlier versions of Ubuntu don't contain up-to-date dependencies. If you're on elementaryOS 6 it's included by default now and you can install it with `sudo apt install vala-language-server`

**Comment by Prince781** [comment]
Anything further? Please let me know. Otherwise I'll close this item.

**Comment by klascano** [comment]
thanks for your reply, i'm agree so i will wait for the new eos release.
