### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by JCWasmx86** [Prince781/vala-language-server#212]
I would like to implement (at least basic) formatting for the VLS. I made this issue to discuss the design, as I would like to avoid doing the same work twice

My proposed initial design:

1. VLS receives the document to format (In this initial format, only entire files will be formatted)
2. An AST is built from the file using libvala.
2.1. If the AST is invalid, just don't format (At least for now)
3. The AST is initially just reformatted with the given [FormattingOptions](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#formattingOptions). No advanced formatting like e.g. splitting long if-Statement conditions over mulltiple lines.
4. The AST is sent back / written to the file.

Are there any objections/criticisms towards this design?

**Comment by Prince781** [comment]
Thanks for your interest in helping out @JCWasmx86!

Yup, you've described what's needed, but all the work is really in steps 3-4. VLS already has the AST of the current file / project. This is updated after every change.

libvala doesn't keep the source references around for tokens and spaces, so you'll have to do some work to analyze those properly. Furthermore, you'll find sometimes that the semantic analyzer has rewritten part of the AST such that the source reference is unrecoverable<sup>[1](#footnote1)</sup>. We could work around this issue by parsing the document without any semantic analysis, but you can worry about that later.

We're creating a new "engine" for VLS, so I'd say this code belongs in `src/codehelp/formatengine.vala`, but you're free to think of somewhere else. A good place to start might be to add something that can convert indentation. Then build on from there. I guess you should make your solution work in general for any range of text, that way we can implement `textDocument/rangeFormatting` as well. 

I also think that in addition to `FormatOptions`, the format engine should support options in `vala-lint.conf` if the file exists in the workspace. I have an idea about adding [vala-lint](https://github.com/vala-lang/vala-lint) to VLS for formatting/linting errors, and _maybe_  you could take a look at their parsing infrastructure for some additional inspiration, although I don't expect `vala-lint` to be amenable to reuse.

And don't forget that you have to add new handlers for these methods in the Server here:
https://github.com/Prince781/vala-language-server/blob/3d3bbae2a1a577aa9e5b5321cdea2a3ca7e6a3fc/src/server.vala#L182

Feel free to ask any questions. I'd be happy to work with you and walk you through the code.

<a name="footnote1">[1]</a>: For example, the analyzer rewrites expressions throwing an error—such as a call to a constructor—with a temporary.

**Comment by benwaffle** [comment]
It would be nice to put the formatting logic in a library, so that you could build a `valafmt` command line tool.

**Comment by JCWasmx86** [comment]
Thanks for your fast replies!

Now after some tinkering, I hit some roadblock, although I did everything described in the spec
Do I have to change something in the plugins, too (E.g. vscode or gnome-builder)? In VSCodium, if I press (Ctrl + Shift + I) or gnome-builder (Ctrl + Alt + I), no "textDocument/formatting" is sent to the server. [My fork](https://github.com/JCWasmx86/vala-language-server).

**Comment by Prince781** [comment]
@JCWasmx86 your formatting code is being called, but nothing is happening yet. You should try to print your payload so you can understand what edits you're generating.

**Comment by Prince781** [comment]
It looks like your text edit ranges need to be fixed:

```
(vala-language-server:51884): vls-DEBUG: 14:16:50.722: server.vala:1473: [textDocument/formatting] called!
(vala-language-server:51884): vls-DEBUG: 14:16:50.722: server.vala:1480: [textDocument/formatting] found good URI ... file:///home/pferro/Projects/valdo/src/main.vala
(vala-language-server:51884): vls-DEBUG: 14:16:50.722: server.vala:1513: sending edits - [
  {
    "range" : {
      "start" : {
        "line" : 0
      },
      "end" : {
        "line" : 2147483647
      }
    },
    "newText" : "\n"
  }
]
```

**Comment by JCWasmx86** [comment]
Thanks for your help!

It "works" now, but I had to recognize, that just indenting line-based will probably not work in the huge majority of cases and end up in a lot of (ugly) code.

I will try to write some sort of tokenizer, so I can reformat it better and be more flexible.

Like:

```
if(variable) {

}
```
will then be a list of some tokens, e.g. `keyword("if"), sym("("), identifier("variable"), sym(")"), sym("{"), sym("}")`.

Although this will increase the development time, this is the far superior approach. So is e.g. reading an editorconfig/vala-lint.conf file and using these files far easier/possible with this approach. 

Libvala sadly doesn't support AFAIK such a tokenizing, so I have to implement it myself.

The line-based indenting will probably be used for `textDocument/rangeFormatting`.

Estimated time:

-Four months

**Comment by Prince781** [comment]
@JCWasmx86

> Libvala sadly doesn't support AFAIK such a tokenizing, so I have to implement it myself.

This is not true. Take a look at `Vala.Scanner`. See also `Vala.Parser` which holds a scanner, which is held by the `Vala.CodeContext`. However the scanner held by the parser is a private field, so...

This project coordinates with upstream. Often we try to work around things but many times we've had to request changes in the compiler to fit our needs. One avenue would be to modify libvala to expose the scanner held by the parser so you can use it for your needs. Then, send a merge request to upstream when you're done.

Another avenue would be to analyze the text contained by the sourceref of a codenode like `Vala.Method`, scan from left to right whitespace and stop when you hit a char. No parsing or tokenization required.

**Comment by colinkiama** [comment]
After looking at [vala-lint](https://github.com/vala-lang/vala-lint), I think that it makes sense for its structure to be reused.

The key difference would be that each check would also have an corresponding action.

The first version of this would only include checks based on the [Generic LSP Formatting Options](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#formattingOptions).

I propose something like this:
1. Checks are performed on the code.
2. Mistakes on each check are recorded.
3. For each check that at least 1 mistake was found for, go through each mistake made and run the action that fixes the mistake.

e.g [`TrailingNewLinesCheck`](https://github.com/vala-lang/vala-lint/blob/master/lib/Checks/TrailingNewlinesCheck.vala) would have a corresponding `TrailingNewLinesAction` that would run if a mistake is found during the check, which adds the a new line to the end of the file.

**Comment by JCWasmx86** [comment]
@colinkiama I start to work from scratch on the branch "formatting"
