### ISSUE TITLE
Support for the @since taglet

### ISSUE THREAD

**Issue by nahuelwexd** [Prince781/vala-language-server#213]
Currently, it's just shown there, but without any format
![image](https://user-images.githubusercontent.com/18204745/126840519-d0244655-9d2d-4322-9de4-9f3215ab6b4b.png)

**Comment by Prince781** [comment]
If we're supposed to render something for `@since`, should we also render something for `[Version (since = "...")]`?

**Comment by nahuelwexd** [comment]
I don't think so, as they've different use cases AFAIU

`[Version (since = "...")]` is just intended to be used by bindings, to allow Vala to warn you if you're using APIs that are not in the version of the library installed onto your system

Those libraries should already expose this info in their docs (exposed to VLS through gir)

**Comment by Prince781** [comment]
@nahuelwexd what do you think about this design?

![Screenshot from 2022-03-08 18-05-38](https://user-images.githubusercontent.com/1341033/157341099-5d25b09c-5b2c-48ca-b096-4affe85f9598.png)

**Comment by nahuelwexd** [comment]
Looks good
