### ISSUE TITLE
Support null-conditional member access

### ISSUE THREAD

**Issue by nehalem501** [Prince781/vala-language-server#215]
The following code compiles fine in the terminal, but the vscode plugin shows errors.

Screenshot:
<img width="499" alt="Screenshot 2021-08-17 at 11 32 34" src="https://user-images.githubusercontent.com/4194367/129702212-6c5f6b67-6364-4671-aef7-09d9284a2204.png">

Code used:
```vala
public class Foo : Object {
    public bool bar;
}

int main(string[] args) {
    Foo? foo = new Foo();
    if (foo.bar == true) { } // Works
    if (foo?.bar == true) { } // Doesn't
    return 0;
}
```

**Comment by Prince781** [comment]
How did you install vala-language-server by the way? Did you compile it or did you install it from a repository? And how did you install Vala?

**Comment by nehalem501** [comment]
I'm on macOS, vala and the language server were installed via homebrew. Vala version is `0.52.5` and vala-language-server version `0.48.3`. (https://formulae.brew.sh/formula/vala, https://formulae.brew.sh/formula/vala-language-server)

I've compiled myself a newer version of the compiler since then (`0.54`), and you were right, there is a mismatch between the compiler version used by the language server and the one I use in the terminal. When manually compiling in the terminal with the older version, I have the same error as in my editor (`vala-0.52 nullable.vala`).

```
$ otool -L vala-language-server 
vala-language-server:
	/usr/local/opt/glib/lib/libglib-2.0.0.dylib (compatibility version 6801.0.0, current version 6801.3.0)
	/usr/local/opt/glib/lib/libgobject-2.0.0.dylib (compatibility version 6801.0.0, current version 6801.3.0)
	/usr/local/opt/glib/lib/libgio-2.0.0.dylib (compatibility version 6801.0.0, current version 6801.3.0)
	/usr/local/opt/libgee/lib/libgee-0.8.2.dylib (compatibility version 9.0.0, current version 9.1.0)
	/usr/local/opt/json-glib/lib/libjson-glib-1.0.0.dylib (compatibility version 601.0.0, current version 601.2.0)
	/usr/local/opt/jsonrpc-glib/lib/libjsonrpc-glib-1.0.1.dylib (compatibility version 3801.0.0, current version 3801.0.0)
	/usr/local/opt/vala/lib/libvala-0.52.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
```

I guess I have to manually recompile the server ?

**Comment by nehalem501** [comment]
After compiling vala-language-server from git and installing it, the issue is not present anymore.

**Comment by Prince781** [comment]
@nehalem501 for future reference: if you install VLS from Homebrew, you should use it with the version Vala installed from Homebrew.
