### ISSUE TITLE
GNOME Builder: Error importing plugin 'vala_langserv' on startup

### ISSUE THREAD

**Issue by v1993** [Prince781/vala-language-server#221]
**Describe the bug**
The GNOME Builder plugin does not seem to be working for me. When staring fr

**Software**
OS and version (e.g. Ubuntu 20.04): KUbuntu 21.04
Code editor (e.g. VSCode): GNOME Builder 3.38.2
Vala Language Server (e.g. git commit, or PPA/AUR version): 4ae7150ad9ee4a5cb9f09fe82834a68cb0150be4
Vala version (`valac --version`): 0.52.5

**To Reproduce**
I've just installed this project according to instructions, that's all I did. Flatpak version that comes with GNOME Builder seems to work fine, but I'd prefer to use system version if possible.

Log:

```
17:53:12.6599                                    (null)[ 60115]:  WARNING: Error importing plugin 'vala_langserv':
Traceback (most recent call last):
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/x86_64-linux-gnu/gnome-builder/plugins/vala_langserv.py", line 202, in <module>
    class VlsSearchProvider(Ide.LspSearchProvider):
  File "/usr/lib/python3/dist-packages/gi/overrides/__init__.py", line 32, in __getattr__
    return getattr(self._introspection_module, name)
  File "/usr/lib/python3/dist-packages/gi/module.py", line 123, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Ide' object has no attribute 'LspSearchProvider'
17:53:12.6600                                   libpeas[ 60115]:  WARNING: Error loading plugin 'vala_langserv'
```

**Comment by Prince781** [comment]
Huh. I guess Builder 3.38 doesn't support IdeLspSearchProvider?

**Comment by Prince781** [comment]
@v1993 check that the above fix works for you on that branch.

**Comment by v1993** [comment]
Yes, that fixes it, thanks!

While we are at it, a question: what files do I need to have per-symbol help with Vala, like shown on screenshot? I've tried installing all kinds of documentation packages, but nothing worked (there is no documentation for glib and gtk3 stuff all the same).

**Comment by Prince781** [comment]
> While we are at it, a question: what files do I need to have per-symbol help with Vala, like shown on screenshot? I've tried installing all kinds of documentation packages, but nothing worked (there is no documentation for glib and gtk3 stuff all the same).

Are you talking about having symbol documentation on hover? For that, VLS searches for GObject Introspection Repository files (ending in `.gir`). You should install `libgirepository-1.0-dev` and then other `-dev` packages for libraries.

**Comment by v1993** [comment]
About symbol doc on hover: I do have that package installed, but there's still no documentation. Should I make a separate issue?

**Comment by Prince781** [comment]
@v1993 please create a discussion for it first. If we determine it's a bug then we can always turn it into an issue.

**Comment by Prince781** [comment]
Or let me know if you found a solution.

**Comment by v1993** [comment]
Yeah, I'll make a discussion once I'll get to it. Too busy with the other stuff for now.
