### ISSUE TITLE
Problem to install Vala Language Server on Fedora 35

### ISSUE THREAD

**Issue by leonardon397** [Prince781/vala-language-server#225]
When I run command `sudo dnf install vala-language-server` or `sudo yum install vala-language-server`, I got followed error bellow:
```
Mistake:
 Problem: conflicting requests
  - the vala-language-server-0.48.3-8.69.aarch64 package does not have a compatible architecture
  - nothing provides json-glib(aarch-64) >= 1.4.4 needed by vala-language-server-0.48.3-8.69.aarch64
  - nothing provides jsonrpc-glib(aarch-64) >= 3.28 needed by vala-language-server-0.48.3-8.69.aarch64
  - nothing provides libvala(aarch-64) >= 0.48.12 needed by vala-language-server-0.48.3-8.69.aarch64
  - nothing provides libvala-0.48.so.0()(64bit) needed by vala-language-server-0.48.3-8.69.aarch64
  - nothing provides glib2(aarch-64) needed by vala-language-server-0.48.3-8.69.aarch64
  - nothing provides ld-linux-aarch64.so.1()(64bit) needed by vala-language-server-0.48.3-8.69.aarch64
  - nothing provides ld-linux-aarch64.so.1(GLIBC_2.17)(64bit) needed by vala-language-server-0.48.3-8.69.aarch64
  - nothing provides libgee(aarch-64) needed by vala-language-server-0.48.3-8.69.aarch64
  - the vala-language-server-0.48.3-8.69.armv7hl package does not have a compatible architecture
  - nothing provides json-glib(armv7hl-32) >= 1.4.4 needed by vala-language-server-0.48.3-8.69.armv7hl
  - nothing provides jsonrpc-glib(armv7hl-32) >= 3.28 needed by vala-language-server-0.48.3-8.69.armv7hl
  - nothing provides libvala(armv7hl-32) >= 0.48.12 needed by vala-language-server-0.48.3-8.69.armv7hl
  - nothing provides glib2(armv7hl-32) needed by vala-language-server-0.48.3-8.69.armv7hl
  - nothing provides ld-linux-armhf.so.3 needed by vala-language-server-0.48.3-8.69.armv7hl
  - nothing provides ld-linux-armhf.so.3(GLIBC_2.4) needed by vala-language-server-0.48.3-8.69.armv7hl
  - nothing provides libgcc_s.so.1(GCC_3.5) needed by vala-language-server-0.48.3-8.69.armv7hl
  - nothing provides libgee(armv7hl-32) needed by vala-language-server-0.48.3-8.69.armv7hl
  - nothing provides libvala-0.48.so.0 needed by vala-language-server-0.48.3-8.69.armv7hl
  - nothing provides libvala-0.48.so.0()(64bit) needed by vala-language-server-0.48.3-8.69.x86_64
```
The command tries to install a version for ARM 64 processors, even though my processor is X64 (that **isn't** same)...
Tries to Install X64 too (that's should be)...

**Trying to run alternative install:**
Firstly, I browsed to https://download.opensuse.org/repositories/home:/Prince781 and I clicked in [Fedora_34](https://download.opensuse.org/repositories/home:/Prince781/Fedora_34), after I clicked in [x86_64](https://download.opensuse.org/repositories/home:/Prince781/Fedora_34/x86_64)...
When I run command `sudo dnf install https://download.opensuse.org/repositories/home:/Prince781/Fedora_34/x86_64/vala-language-server-0.48.3-8.1.x86_64.rpm`, I got followed error bellow:
```
Mistake:
  Problem: conflicting requests
   - nothing provides libvala-0.48.so.0()(64bit) needed by vala-language-server-0.48.3-8.69.x86_64
```
When I run command `sudo dnf install https://download.opensuse.org/repositories/home:/Prince781/Fedora_34/x86_64/vala-language-server-gb-plugin-0.48.3-8.1.x86_64.rpm`, I got error bellow (It's because I don't have Vala Lnaguage Server installed, because of above error, that I discribed)
```
Mistake:
  Problem: conflicting requests
   - nothing provides vala-language-server = 0.48.3-8.1 needed by vala-language-server-gb-plugin-0.48.3-8.1.x86_64
```
Packages [vala-language-server-debuginfo-0.48.3-8.1.x86_64.rpm](https://download.opensuse.org/repositories/home:/Prince781/Fedora_34/x86_64/vala-language-server-debuginfo-0.48.3-8.1.x86_64.rpm) and [vala-language-server-debugsource-0.48.3-8.1.x86_64.rpm](https://download.opensuse.org/repositories/home:/Prince781/Fedora_34/x86_64/vala-language-server-debugsource-0.48.3-8.1.x86_64.rpm), I got successful to install.
 
I installed libvala with version 0.54.3 64bit and I tried all of them again...

remarks: I translated the log in my GNOME Console on Google Translator, because my OS is in Brazilian Portugese...

### Software
OS: Fedora Linux 35 Workstation Edition x86_64 (64 bit) with kernel version 5.14.10
Code editor (e.g. VSCode): VSCode and GNOME Builder
Vala version (`valac --version`): Vala 0.54.3

**Comment by albfan** [comment]
I looked into this and build the package from https://copr.fedorainfracloud.org/coprs/prince781/vala-language-server/

Have no idea how copr contributions works so I will just put the patches here:

[patches.zip](https://github.com/Prince781/vala-language-server/files/7697023/patches.zip)

**Comment by albfan** [comment]
Wonder if instructions for fedora should point to copr instead of opensuse

**Comment by amz-x** [comment]
I have it built on my COPR repo, latest build is here:
https://copr.fedorainfracloud.org/coprs/amz/extras/build/3070587/

**Comment by Prince781** [comment]
I've updated the OBS repository and added a build for Fedora 35. So now you should be able to get it from the download page.

**Comment by stsdc** [comment]
![image](https://user-images.githubusercontent.com/6031763/146992617-22ca581f-de1a-4aa7-9cfa-26fd37e7a9df.png)
@Prince781  Only Fedora 33 and 32 are available :grimacing:

**Comment by Prince781** [comment]
@stsdc it looks like the Fedora 35 package is placed under the "Unknown" category. Strange.
![Screenshot from 2021-12-21 23-52-05](https://user-images.githubusercontent.com/1341033/147037621-3dc02820-48c9-4b45-b8fa-e72c61543de8.png)

I'm closing this since the package has been added, but feel free to reopen if there's another problem with Fedora 35.

**Comment by leonardon397** [comment]
> I've updated the OBS repository and added a build for Fedora 35. So now you should be able to get it from the download page.

Thanks! Now, I got it! 👏‍👏‍👏‍👏‍👏‍👏‍👏‍👏‍👏‍👏‍👏‍😃😃😃😃😃😃😃😃
