### ISSUE TITLE
Make it subproject friendly

### ISSUE THREAD

**Issue by esodan** [Prince781/vala-language-server#230]
I would like to add VLS to GVLS test suite. GVls has a LSP Vala Client, so add an independent server is good test scenario.

Also I would like to use VLS as a Meson subproject, in order to do so I need you set to a variable the VLS executable.

```
vls = executable(...)
```

So GVls can execute VLS server and test it and use it as a Meson subproject.

This could also help to fix #227

**Comment by Prince781** [comment]
I think you'd have a better idea of what's needed for your use case than I do. I have a rough idea, but I think a PR from you would be more fruitful.

**Comment by esodan** [comment]
Done. upstream.
