### ISSUE TITLE
Shared Symbol DB

### ISSUE THREAD

**Issue by esodan** [Prince781/vala-language-server#232]
GVLS is constructing a Database for Symbols in the system, by parsing both VAPI for symbols and GIR files for documentation (also can query documentation from [valadoc.org](https://valadoc.org)), can help on completion and hover requests, may VLS wants to use it too.

GVLS is providing a tool to create the DB and fill it using [VDA](https://gitlab.gnome.org/esodan/libvda) and a SymbolDb provider that can be shared with both projects.

Look at GVLS upstream.

**Comment by Prince781** [comment]
We don't use any extra infrastructure—we merely refer to the `Vala.Symbol`s in the code contexts that we keep track of.

**Comment by esodan** [comment]
Currently, this DB was focused to store documentation for symbols in the system, from parsing both VAPI and GIR files. Now on is possible to have persistent store of symbols both system and per-project. Per-project is one of the solved issues by using a parsed code and `Vala.Symbol`, but what about large projects where compilation requires seconds to be completed? So parse once, store in a DB the ones you found for future access, only updated once a compilation is done, providing fast access to symbols in the system and in a large project.

If you are not interested. Feel free to close this issue.

**Comment by Prince781** [comment]
Right now I'm investigating other ways of improving performance here, using multithreading and possibly keeping a code context per source file rather than per build target. I'll reopen this if I reconsider it.
