### ISSUE TITLE
signatureHelp for printf-style functions

### ISSUE THREAD

**Issue by Prince781** [Prince781/vala-language-server#55]
Currently, a function like `printf()` gets signature help for just the string and the varargs, like this:

![](https://i.imgur.com/qbpYb35.png)

We would like to analyze the format string so that in the above example, the signature help is `void printf (string format, string arg1, int arg2)`. If there are no arguments detected in the format string, the signature help should just display `printf (string format)`

**Comment by Prince781** [comment]
This may be a good newcomer task, but it shouldn't be handled until after #39 is merged.

**Comment by Cogitri** [comment]
Heya,

I'd like to give this a go but to be honest I'm a bit lost as to where I should start to implement this since the code base is rather big

**Comment by Prince781** [comment]
@Cogitri a good place to start would be where signature help is computed, in `Vls.SignatureHelpEngine.show_help()`.

Here is where we perform analysis when the cursor is at a method call. This analysis discovers the precise method we are referring to (`explicit_sym`) and the *formal* parameters of that method (`param_list`). You might have to have a special case for printf-style methods and analyze (one of) the actual arguments passed into the Vala.MethodCall (see the commented-out code for getting `arg_list`), the format string, in order to populate `param_list` with `Vala.Parameter`s you generate on the fly.

https://github.com/benwaffle/vala-language-server/blob/bfd6d5aa0c4616791c55c62cdd057f5706019e82/src/codehelp/signaturehelpengine.vala#L97

Here is where we represent a callable symbol in an aesthetic way, in `Vls.CodeHelp.get_callable_representation()`. Here, you might have to add a parameter that is a list of synthetic formal parameters to replace the ellipsis with. It should be an optional parameter, like `List<Vala.Parameter>? ellipsis_overrides = null`

https://github.com/benwaffle/vala-language-server/blob/bfd6d5aa0c4616791c55c62cdd057f5706019e82/src/codehelp/codehelp.vala#L212

I'm sure there's more I can explain to help you, so feel free to ask me more questions either here or on IRC/Element.

**Comment by Cogitri** [comment]
Thanks for the detailed explanation, I think that's enough to get me going! 👍
I'll look into it on a few days

**Comment by Cogitri** [comment]
OK, I think I have most of the pieces in place now, but I'm not quite sure how to do:

> In Vls.SymbolExtractor.resolve_typed_expression(), the part where we generate a Vala.MethodCall from a FakeMethodCall must be changed to generate fake arguments.

I suppose I would have to loop over the `ArrayList<FakeExpr>` I added to `FakeMethodCall` here:

https://github.com/benwaffle/vala-language-server/blob/a22be6b8faf7099db5b04e92ffedcb1e4792828c/src/codehelp/symbolextractor.vala#L432

like so: 

```
foreach (var fake_arg in fake_mc.argumens) {
    var e  = New Vala.<SomeExpression> ();
    expr.add_argument (e);
}
```

Or by recursing into `resolve_typed_expression()` again, if required. I'm not quite sure what subclass for `Vala.Expression` I'd have to use here for actually adding arguments (and how I'd reconstruct it from the `FakeExpr`)

**Comment by Prince781** [comment]
@Cogitri, I'm sorry for taking some time to get back to this. I appreciate the work you've done and if you happen to no longer be interested in this issue (seeing as you've migrated some of your projects to Rust), then I would perfectly understand. The work you've done is useful as it is and I will still credit you in the release notes.

With that out of the way, now a note on the issue: I think that bullet point 2 was a red herring. I think it shouldn't be necessary to modify `resolve_typed_expression()` after all, since your work in `SignatureHelpEngine.show_help()` should generate a modified `param_list` (or perhaps a `fake_param_list`) containing the additional synthetic arguments.
